config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('polls.urls'))
]

polls/urls.py
from django.urls import path

from polls.views import (
    homepage,
    questions_list,
    question_detail,
    question_vote,
    choice_new,
    question_new,
    BlogDeleteView
)

app_name = 'polls'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('questions/', questions_list, name='questions_list'),
    path('questions/<int:question_id>/', question_detail, name='question_detail'),
    path('questions/<int:question_id>/vote/', question_vote, name='question_vote'),
    path('questions/new/', choice_new, name='choice_new'),
    path('questions/add/', question_new, name='question_new'),
    path('questions/<int:question_id>/delete/', BlogDeleteView.as_view(), name='question_delete'),

]

polls/models.py
from django.db import models
from django.urls import reverse


class Question(models.Model):
    text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('data published', null=True)

    def __str__(self):
        return self.text

    # def get_absolute_url(self):
    #     return reverse('polls:question_detail', args=[str(self.id)])
    #

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)
    is_true = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text} - {self.is_true}'

polls/forms.py
from django import forms
from polls.models import Question, Choice


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['question', 'text', 'votes', 'is_true']


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text', 'pub_date']

polls/views.py
from django.contrib import messages
from django.contrib.messages import SUCCESS, ERROR
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView

from polls.forms import QuestionForm, ChoiceForm
from polls.models import Question, Choice


def homepage(request):
    return render(request, 'home.html')


def questions_list(request):
    questions = Question.objects.all()

    context = {
        "questions": questions
    }

    return render(request, 'polls/question.html', context=context)


def question_detail(request, question_id):
    question = get_object_or_404(Question, id=question_id)

    context = {
        "question": question,
    }

    return render(request, 'polls/question_detail.html', context=context)


def question_vote(request, question_id):
    choice = request.POST['choice']
    question = get_object_or_404(Question, id=question_id)
    try:
        selected_choice = question.choices.get(pk=choice)
    except Choice.DoesNotExist:
        raise Http404("Choice doesn't exist.")
    else:
        selected_choice.votes += 1
        selected_choice.save()
        if selected_choice.is_true:
            messages.add_message(request, SUCCESS, 'Your choice is correct.')
            return HttpResponse('Your choice is correct.')
        else:
            messages.add_message(request, ERROR, 'Your choice is incorrect.')
            return HttpResponse('Your choice is incorrect.')
    # return redirect("polls:questions_list")


def choice_new(request):
    form = ChoiceForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("polls:questions_list")
    return render(request, 'choices_new.html', {"form": form})


def question_new(request):
    form = QuestionForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("polls:questions_list")
    return render(request, 'question_new.html', {"form": form})


class BlogDeleteView(DeleteView):
    model = Question
    template_name = 'question_delete.html'
    success_url = reverse_lazy('polls:homepage')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Homepage</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg bg-primary-subtle">
    <div class="container">
        <a class="navbar-brand" href="{% url 'polls:homepage' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'polls:questions_list' %}">Questions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://127.0.0.1:8000/admin/">Admin</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

{#New choices#}

<header>
    <div class="nav-left">
        <h1><a href="{% url 'polls:homepage' %}"></a></h1>
    </div>
    <div class="nav-right">
        {% if questions %}
            <a href="{% url 'polls:choice_new' %}">Add a new choice</a>
        {% endif %}
    </div>
</header>

{#New questions#}


<header>
    <div class="nav-left">
        <h1><a href="{% url 'polls:homepage' %}"></a></h1>

    </div>
    <div class="nav-right">
        {% if questions %}
            <a href="{% url 'polls:question_new' %}">Add a new question</a>
        {% endif %}
    </div>
</header>

{% block content %}


{% endblock %}

</body>
</html>

templates/choices_new.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Add</button>
    </form>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <p class="h1">You can find questions here!</p>
        <br>
        <a href="{% url 'polls:questions_list' %}">Click to questions</a>
    </div>
    <img
            src="https://raw.githubusercontent.com/mdn/beginner-html-site/gh-pages/images/firefox-icon.png"
            alt="Firefox icon"/>

{% endblock %}

templates/polls/question.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Questions list page</h2>

        <div class="list-group">
            {% for question in questions %}
                <a href="{% url 'polls:question_detail' question.id %}">
                    <button type="button" class="list-group-item list-group-item-action">{{ question.text }}</button>
                </a>
            {% endfor %}
        </div>


    </div>
{% endblock %}

templates/polls/question_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form action="{% url 'polls:question_vote' question.id %}" method="post">
            {% csrf_token %}
            <b>Text:</b> {{ question.text }}
            <br>
            <b>Publication date:</b> {{ question.pub_date }}
            {% for choice in question.choices.all %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="choice" value="{{ choice.id }}"
                           id="{{ choice.id }}">
                    <label class="form-check-label" for="{{ choice.id }}">
                        {{ choice.text }}
                    </label>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Submit</button>
            <br>
            <br>
            <a class="mt-5" href="{% url 'polls:questions_list' %}">
                <button type="button" class="btn btn-outline-primary">Back to questions</button>
            </a>
        </form>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>


    <div class="post-entry">
    </div>
    <a href="{% url 'polls:question_delete' question.id %}">Delete</a>
{% endblock content %}

templates/question_new.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Add</button>
    </form>

{% endblock content %}